### ISSUE TITLE
Plugin throwing exception with Kafka 2.7.0

### ISSUE THREAD

**Issue by SledgeHammer01** [jcustenborder/kafka-connect-spooldir#162]
Windows 10 Pro x64
Java Oracle SDK 11.0.9
Kafka 2.13-2.70
jcustenborder-kafka-connect-spooldir-2.0.54

Properties file looks like:

```
# general settings for CSV file connector

name=file-connector

connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector

tasks.max=1
input.path=c:/inetpub/sftproot
input.file.pattern=^\^?[A-Za-z]+\.[Cc][Ss][Vv]$
error.path=c:/inetpub/sftproot/error
finished.path=c:/inetpub/sftproot/finished
halt.on.error=false
topic=sftp-topic
csv.first.row.as.header=true
key.schema={\n  \"name\": \"org.xxx.csv.RecordKey\",\n  \"type\": \"STRUCT\",\n  \"isOptional\": true,\n  \"fieldSchemas\": {\n  }\n}\n
value.schema={\n  \"name\": \"org.xxx.csv.Record\",\n  \"type\": \"STRUCT\",\n  \"isOptional\": false,\n  \"fieldSchemas\": {\n    \"Date\": {\n      \"type\": \"STRING\",\n      \"isOptional\": false\n    },\n    \"Open\": {\n      \"type\": \"FLOAT64\",\n      \"isOptional\": false\n    },\n    \"High\": {\n      \"type\": \"FLOAT64\",\n      \"isOptional\": false\n    },\n    \"Low\": {\n      \"type\": \"FLOAT64\",\n      \"isOptional\": false\n    },\n    \"Close\": {\n      \"type\": \"FLOAT64\",\n      \"isOptional\": false\n    },\n    \"Adj Close\": {\n      \"type\": \"FLOAT64\",\n      \"isOptional\": false\n    },\n    \"Volume\": {\n      \"type\": \"INT64\",\n      \"isOptional\": false\n    }\n  }\n}\n

transforms=HeaderToKey,RenameField

transforms.HeaderToKey.type=org.xxx.kafka.connect.smt.HeaderToKey
transforms.HeaderToKey.headers=file.name
transforms.HeaderToKey.aliases=symbol
transforms.HeaderToKey.standardizeFileName=true

transforms.RenameField.type=org.apache.kafka.connect.transforms.ReplaceField$Value
transforms.RenameField.renames=Date:date,Open:open,High:high,Low:low,Close:close,Adj Close:adjustedClose,Volume:volume

```

The HeaderToKey transform is mine. It works with Kafka 2.6.0 / Spooldir 2.0.43, but I commented out all the transforms just to be sure that wasn't the issue. When I run the startup-connect.bat, I get an exception:

```
[2021-01-06 13:58:59,775] ERROR WorkerConnector{id=file-connector} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonKey
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.hasAsKey(JacksonAnnotationIntrospector.java:1080)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:451)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:378)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:343)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:190)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:323)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:272)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:591)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4731)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4567)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
        at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1847)
        at com.github.jcustenborder.kafka.connect.utils.jackson.SchemaSerializationModule$Deserializer.deserialize(SchemaSerializationModule.java:190)
        at com.github.jcustenborder.kafka.connect.utils.jackson.SchemaSerializationModule$Deserializer.deserialize(SchemaSerializationModule.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4591)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3546)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSpoolDirSourceConnectorConfig.readSchema(AbstractSpoolDirSourceConnectorConfig.java:314)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSpoolDirSourceConnectorConfig.<init>(AbstractSpoolDirSourceConnectorConfig.java:111)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnectorConfig.<init>(SpoolDirCsvSourceConnectorConfig.java:125)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector.config(SpoolDirCsvSourceConnector.java:39)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector.config(SpoolDirCsvSourceConnector.java:26)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceConnector.start(AbstractSourceConnector.java:33)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSpoolDirSourceConnector.start(AbstractSpoolDirSourceConnector.java:52)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:185)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:210)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:332)
        at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:140)
        at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:117)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonKey
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 46 more
[2021-01-06 13:58:59,777] ERROR Failed to create job for C:\PROGRA~1\KAFKA_~1.0\bin\..\config\file-connector.properties (org.apache.kafka.connect.cli.ConnectStandalone)
[2021-01-06 13:58:59,778] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to transition connector file-connector to state STARTED
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:118)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to transition connector file-connector to state STARTED
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:335)
        at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:140)
        at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:117)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonKey
        at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.hasAsKey(JacksonAnnotationIntrospector.java:1080)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:451)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:378)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:343)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:190)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:323)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:272)
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:591)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4731)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4567)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
        at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1847)
        at com.github.jcustenborder.kafka.connect.utils.jackson.SchemaSerializationModule$Deserializer.deserialize(SchemaSerializationModule.java:190)
        at com.github.jcustenborder.kafka.connect.utils.jackson.SchemaSerializationModule$Deserializer.deserialize(SchemaSerializationModule.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4591)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3546)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSpoolDirSourceConnectorConfig.readSchema(AbstractSpoolDirSourceConnectorConfig.java:314)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSpoolDirSourceConnectorConfig.<init>(AbstractSpoolDirSourceConnectorConfig.java:111)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnectorConfig.<init>(SpoolDirCsvSourceConnectorConfig.java:125)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector.config(SpoolDirCsvSourceConnector.java:39)
        at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector.config(SpoolDirCsvSourceConnector.java:26)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSourceConnector.start(AbstractSourceConnector.java:33)
        at com.github.jcustenborder.kafka.connect.spooldir.AbstractSpoolDirSourceConnector.start(AbstractSpoolDirSourceConnector.java:52)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:185)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:210)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:332)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonKey
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 46 more
```

**Comment by jcustenborder** [comment]
@SledgeHammer01, @Hubbitus, @arijitmazumdar can you give this version a try? [jcustenborder-kafka-connect-spooldir-2.0-SNAPSHOT.zip](https://github.com/jcustenborder/kafka-connect-spooldir/files/5788794/jcustenborder-kafka-connect-spooldir-2.0-SNAPSHOT.zip)

**Comment by SledgeHammer01** [comment]
> @SledgeHammer01, @Hubbitus, @arijitmazumdar can you give this version a try? [jcustenborder-kafka-connect-spooldir-2.0-SNAPSHOT.zip](https://github.com/jcustenborder/kafka-connect-spooldir/files/5788794/jcustenborder-kafka-connect-spooldir-2.0-SNAPSHOT.zip)

Connect starts up now. I'll have to do more testing to know if it works though :).
